// Overworld HD-2D diorama for one GameMap: streamed terrain chunks (tops, cliffs, liquids, soft fringes), tall grass,
// ground decor and props with procedural variants, lamps, climate tints + snow dusting, sky & time of day, weather +
// ambient particles, actors, FX and the DOM overlay. Implements the WorldView contract; chunks are built lazily around
// the focus inside a per-frame budget and evicted when far (content/render.json "streaming"), so 1024² maps load fast
// and memory stays bounded. Infinite maps (GameMap.infinite) stream an unbounded chunk grid: a first build stage
// ensures the world chunks it reads (budgeted generation), idle frames prefetch world chunks ahead of the player,
// heights / climate live in toroidal textures and far blocks / provider chunks are released periodically.
import * as THREE from 'three'
import { CONTENT } from '../../shared/content/index.ts'
import type { GameMap } from '../../shared/types.ts'
import type { ActorOptions, AssetStore, HD2DRenderer, PostParams, RenderView, WorldView, WorldWeather } from '../contracts.ts'
import {
  RENDER, dirFromAngles, hexToRgb, lerpHex, lightingTier, qualityPreset, sampleLighting, sunState,
  type LightingState, type QualityPreset, type StaticLighting, type Vec3,
} from './config.ts'
import { isHD2DRendererExt } from './hd2d.ts'
import { updateSpriteLighting } from './sprite-lighting.ts'
import { cameraPitch, cameraYaw } from './sprite-utils.ts'
import { createActorImpl, createCreatureActorImpl, type ActorContext, type ActorEntry } from './world/actors.ts'
import { createTerrainAtlas, terrainAtlasKeys } from './world/atlas.ts'
import { createCameraRig, type CameraBounds } from './world/camera.ts'
import { applySnowDust, bindClimate, createClimate, setSnowCover, type ClimateGrid } from './world/climate.ts'
import { tileOf } from './world/coords.ts'
import { createDecorLayer } from './world/decor.ts'
import { createFringeLayer } from './world/fringe.ts'
import { createFootsteps, type StepActor } from './world/footsteps.ts'
import { createReflections } from './world/reflections.ts'
import { createFxSystem } from './world/fx.ts'
import { createGrassLayer, type GrassBender } from './world/grass.ts'
import { createLeafSystem } from './world/leaves.ts'
import { createLightRig, type LightSource } from './world/lights.ts'
import { createLiquidMaterials } from './world/liquids.ts'
import { applyOcclusion, bindOcclusion, setOcclusionView } from './world/occlusion.ts'
import { createOverlayLayer, tagOverSprite, type SpriteFootprint } from './world/overlay.ts'
import { createAurora, createParticleField, type ParticleField } from './world/particles.ts'
import { createPropLayer, type Canopy, type PropChunk, type ShaftAnchor } from './world/props.ts'
import { createQuestTrail } from './world/quest-trail.ts'
import { applySceneLight, createSceneLight, patchSceneLight, sceneLightUniforms } from './world/scene-light.ts'
import { createShafts } from './world/shafts.ts'
import { createSkyRig } from './world/sky.ts'
import { updateSpriteShadows } from './sprite-shadow.ts'
import { createStreamer, type ChunkSlot, type StreamFrame, type Streamer, type StreamStats } from './world/streamer.ts'
import { buildChunk, createHeightField, createTerrainSampler, sampleSurfaceHeight, sampleWalkHeight, type HeightField, type TerrainSampler } from './world/terrain.ts'
import { updateWind } from './world/wind.ts'

/** Everything built for one terrain chunk. */
interface ChunkData {
  group: THREE.Group
  terrain: THREE.Mesh[]
  grass: THREE.InstancedMesh[]
  decor: THREE.InstancedMesh[]
  props: PropChunk | null
  lights: LightSource[]
  /** Tree gaps where light shafts can fall (from the prop stage). */
  anchors: ShaftAnchor[]
  /** Shader programs of the finished chunk are linked (compileAsync): shown only then, so a material seen for the
   * first time never stalls a frame on a synchronous compile. */
  ready: boolean
  compiling: boolean
  disposed: boolean
}

/** WorldView plus renderer diagnostics (sandbox / debug overlay). */
export interface WorldViewExt extends WorldView {
  /** Chunk streaming counters of the loaded map. */
  readonly streaming: StreamStats | null
  /** Milliseconds spent in the last loadMap (renderer part). */
  readonly loadMs: number
  /** Infinite maps: world chunks generated by the prefetch ring / ensure stage, last prefetch cost (ms). */
  readonly worldGen: { prefetched: number; ensured: number; lastMs: number; maxMs: number; retainMs: number } | null
  /** Chunks shown by the compile timeout before their programs were linked (should stay 0). */
  readonly compileTimeouts: number
  /** Lighting diagnostics (automation / dev overlay): light-field lights in use, cloud shadow strength, wetness, light shafts shown. */
  readonly lightDebug: { fieldLights: number; sources: number; cloud: number; wet: number; shafts: number; lamps: number }
  /** Re-reads tiles / objects of the loaded map (after runtime edits such as an opened gate) and rebuilds chunks. */
  invalidateMap(): void
}

const yieldFrame = () => new Promise<void>((r) => setTimeout(r, 0))
/** Build stages per chunk (ensure world chunks, terrain, grass, props, decor). */
const STAGE_COUNT = 5

export function createWorldView(renderer: HD2DRenderer, assets: AssetStore, overlay: HTMLElement): WorldViewExt {
  const ext = isHD2DRendererExt(renderer) ? renderer : null
  const settings = () => ext?.settings ?? CONTENT.config.defaultSettings
  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)')
  const quality = (): QualityPreset => ext?.quality ?? qualityPreset(settings().quality)
  const chunkSize = CONTENT.config.world.chunk
  const S = RENDER.streaming

  const scene = new THREE.Scene()
  scene.name = 'overworld'
  const rig = createCameraRig()
  const camera = rig.camera
  const sky = createSkyRig(scene)
  const atlas = createTerrainAtlas(assets, terrainAtlasKeys())
  // terrain takes the occlusion cutaway too: cave wall masses and cliffs south of the player would hide it
  const matte = applySceneLight(applyOcclusion(applySnowDust(new THREE.MeshLambertMaterial({ map: atlas.texture, vertexColors: true }), false)), true)
  const glossy = applySceneLight(applyOcclusion(applySnowDust(new THREE.MeshPhongMaterial({
    map: atlas.texture, vertexColors: true, shininess: RENDER.terrain.glossy.shininess,
    specular: new THREE.Color().setRGB(...hexToRgb(RENDER.terrain.glossy.specular), THREE.SRGBColorSpace),
  }), false)), true)
  const liquids = createLiquidMaterials()
  const grass = createGrassLayer(assets, atlas, { trample: true })
  const props = createPropLayer(assets, { occlusion: true })
  const decor = createDecorLayer()
  const fringe = createFringeLayer(atlas.texture)
  const lights = createLightRig()
  const sceneLight = createSceneLight()
  const shafts = createShafts()
  const fx = createFxSystem()
  const leaves = createLeafSystem(Math.max(...Object.values(RENDER.physics.tiers).map((t) => t.leaves)))
  const footsteps = createFootsteps((x, z, _y, amp) => liquids.ripple(x, z, amp))
  const reflections = createReflections()
  const questTrail = createQuestTrail()
  const overlayLayer = createOverlayLayer(overlay)
  const aurora = createAurora()
  const chunkRoot = new THREE.Group()
  chunkRoot.name = 'chunks'
  const actorsGroup = new THREE.Group()
  actorsGroup.name = 'actors'
  scene.add(chunkRoot, lights.group, shafts.mesh, fx.group, footsteps.group, leaves.mesh, actorsGroup, aurora.mesh, questTrail.glow, questTrail.mesh)
  bindOcclusion(scene)

  const registry = new Set<ActorEntry>()
  const yaw = { value: 0 }
  let map: GameMap | null = null
  let sampler: TerrainSampler | null = null
  let climate: ClimateGrid | null = null
  let streamer: Streamer<ChunkData> | null = null
  let heights: HeightField | null = null
  let maxTop = 0
  const IS = S.infinite
  let retainT = 0
  const gen = { prefetched: 0, ensured: 0, lastMs: 0, maxMs: 0, retainMs: 0 }
  let compileTimeouts = 0
  let lightsDirty = false
  let loadMs = 0
  const mapSize = new THREE.Vector2(1, 1)
  const fields = new Map<string, ParticleField>()
  let fieldScale = quality().particleScale
  let builtGrassPerTile = Math.round(quality().grassPerTile)
  let builtDecor = quality().decorDensity
  let builtFringe = quality().terrainFringe
  let poolSize = -1
  let time = 0
  let atlasT = 0
  let minutes = CONTENT.config.time.startMinutes
  const focus = new THREE.Vector3()
  const lastFocus = new THREE.Vector3()
  const focusVel = new THREE.Vector2()
  const weatherTarget: WorldWeather = { kind: 'clear', intensity: 0 }
  const weatherLevels = new Map<string, number>()
  /** First update after a map load: weather and ambient particles start at full level instead of fading in. */
  let snapAmbience = false
  let shadowsCast = true
  let debugLamps = 0
  let physicsTier = ''
  /** Snow built up by the weather, 0..1 of render.json snowCover.max. */
  let snowLevel = 0
  let canopyT = 0
  const post: Partial<PostParams> = {}
  const stepActors = new WeakMap<ActorEntry, StepActor>()
  const stepList: StepActor[] = []

  const actorCtx: ActorContext = {
    assets,
    root: actorsGroup,
    overlay: overlayLayer,
    registry,
    yaw,
    inGrassAt: (x, y) => !!sampler && !!sampler.terrain(tileOf(x), tileOf(y))?.tallGrass,
    groundAt: (x, z) => (sampler ? sampleSurfaceHeight(sampler, x, z) : 0),
  }

  const staticPreset = (): StaticLighting | null => {
    if (!map) return null
    if (map.kind === 'cave') return RENDER.cave
    if (map.kind === 'interior' || !map.outdoor) return RENDER.interior
    return null
  }

  // --- chunk streaming --------------------------------------------------------

  const _frustum = new THREE.Frustum()
  const _pm = new THREE.Matrix4()
  const _box = new THREE.Box3()

  function disposeChunk(slot: ChunkSlot<ChunkData>): void {
    const d = slot.data
    d.disposed = true
    for (const m of d.terrain) { m.removeFromParent(); m.geometry.dispose() }
    grass.disposeChunk(d.grass)
    decor.disposeChunk(d.decor)
    if (d.props) props.disposeChunk(d.props)
    d.group.removeFromParent()
    d.terrain = []; d.grass = []; d.decor = []; d.props = null
    lightsDirty = true
  }

  function newStreamer(m: GameMap, s: TerrainSampler): Streamer<ChunkData> {
    const infinite = !!m.infinite
    const cols = infinite ? Infinity : Math.ceil(m.width / chunkSize), rows = infinite ? Infinity : Math.ceil(m.height / chunkSize)
    const margin = IS.ensureMargin
    return createStreamer<ChunkData>({
      cols, rows, chunk: chunkSize,
      create(cx, cy) {
        const group = new THREE.Group()
        group.name = `chunk:${cx},${cy}`
        chunkRoot.add(group)
        // infinite maps: lights are read in the props stage (after the world chunks exist)
        if (!infinite) lightsDirty = true
        return { group, terrain: [], grass: [], decor: [], props: null, lights: infinite ? [] : props.lightsOf(cx, cy), anchors: [], ready: false, compiling: false, disposed: false }
      },
      stages: [
        // world chunks this render chunk reads (neighbour tiles, prop footprints, lights); generation is budgeted
        (slot, deadline) => {
          if (!infinite) return true
          const x0 = slot.cx * chunkSize, y0 = slot.cy * chunkSize
          const rect = { x0: x0 - margin, y0: y0 - margin, x1: x0 + chunkSize + margin, y1: y0 + chunkSize + margin }
          if (s.ready(rect)) return true
          gen.ensured++
          return s.ensure(rect, deadline)
        },
        (slot) => {
          if (infinite) {
            const x0 = slot.cx * chunkSize, y0 = slot.cy * chunkSize, c = RENDER.fields.cell
            climate?.touch({ x0: x0 - c, y0: y0 - c, x1: x0 + chunkSize + c, y1: y0 + chunkSize + c })
            heights?.writeChunk(slot.cx, slot.cy, chunkSize)
            maxTop = Math.max(maxTop, s.maxTop)
          }
          const g = buildChunk({ sampler: s, rect: (k) => atlas.rect(k), climate }, slot.cx, slot.cy, chunkSize)
          const meshes: THREE.Mesh[] = []
          if (g.solid) {
            const mesh = new THREE.Mesh(g.solid, [matte, glossy])
            mesh.castShadow = true
            mesh.receiveShadow = true
            meshes.push(mesh)
          }
          if (g.water) { const w = new THREE.Mesh(g.water, liquids.water); w.renderOrder = 2; meshes.push(w) }
          if (g.falls) { const f = new THREE.Mesh(g.falls, liquids.falls); f.renderOrder = 3; meshes.push(f) }
          if (g.lava) meshes.push(new THREE.Mesh(g.lava, liquids.lava))
          if (builtFringe) {
            const f = fringe.build(s, slot.cx, slot.cy, chunkSize, (k) => atlas.rect(k), climate)
            if (f) { const fm = new THREE.Mesh(f, fringe.material); fm.receiveShadow = true; fm.renderOrder = 1; meshes.push(fm) }
          }
          for (const mesh of meshes) { mesh.name = 'terrain'; slot.data.group.add(mesh) }
          slot.data.terrain = meshes
          patchSceneLight(slot.data.group)
          return true
        },
        (slot) => {
          slot.data.grass = grass.buildChunk(s, slot.cx, slot.cy, chunkSize, builtGrassPerTile, climate)
          for (const mesh of slot.data.grass) slot.data.group.add(mesh)
          patchSceneLight(slot.data.group)
          return true
        },
        (slot, deadline) => {
          const c = props.buildChunk(slot.cx, slot.cy, deadline)
          if (!c) return false
          slot.data.props = c
          props.applyShadows(c)
          for (const mesh of c.meshes) slot.data.group.add(mesh)
          patchSceneLight(slot.data.group)
          slot.data.anchors = c.anchors
          if (infinite) slot.data.lights = props.lightsOf(slot.cx, slot.cy)
          lightsDirty = true
          return true
        },
        (slot) => {
          slot.data.decor = decor.build(s, slot.cx, slot.cy, chunkSize, climate, props.blockedIn(slot.cx, slot.cy), builtDecor, (k) => atlas.averageColor(k))
          for (const mesh of slot.data.decor) slot.data.group.add(mesh)
          patchSceneLight(slot.data.group)
          return true
        },
      ],
      dispose: disposeChunk,
    })
  }

  function streamFrame(q: QualityPreset): StreamFrame {
    _pm.multiplyMatrices(camera.projectionMatrix, camera.matrixWorldInverse)
    _frustum.setFromProjectionMatrix(_pm)
    const lo = sampler ? sampler.skirt : -2
    const top = map?.infinite ? Math.max(maxTop, IS.assumedTopLevel * CONTENT.config.world.levelHeight) : maxTop
    return {
      now: time,
      focusX: rig.target.x, focusZ: rig.target.z,
      radius: q.viewRadius, keepRadius: q.viewRadius + S.keepMargin, maxChunks: q.maxChunks,
      budgetMs: S.budgetMs, catchUpBudgetMs: S.catchUpBudgetMs, disposePerFrame: S.disposePerFrame,
      offscreenPenalty: S.offscreenPenalty, moveLookAhead: S.moveLookAhead, velX: focusVel.x, velZ: focusVel.y,
      inView(cx, cy) {
        _box.min.set(cx * chunkSize, lo, cy * chunkSize)
        _box.max.set((cx + 1) * chunkSize, top + S.boundsHeight, (cy + 1) * chunkSize)
        return _frustum.intersectsBox(_box)
      },
    }
  }

  /** Links the programs of finished chunks in the background (KHR_parallel_shader_compile) before they show; a
   * timeout shows them anyway. Returns the pending compiles. */
  function compileFinished(stages: number): Promise<unknown>[] {
    const out: Promise<unknown>[] = []
    if (!streamer) return out
    for (const slot of streamer.slots.values()) {
      const d = slot.data
      if (d.ready || d.compiling || slot.stage < stages) continue
      if (!S.compileAsync) { d.ready = true; continue }
      d.compiling = true
      const done = () => { d.ready = true; d.compiling = false }
      const timer = setTimeout(() => { if (!d.ready) compileTimeouts++; done() }, S.compileTimeoutMs)
      out.push(renderer.gl.compileAsync(d.group, camera, scene).catch(() => undefined).then(() => { clearTimeout(timer); if (!d.disposed) done() }))
    }
    return out
  }

  function updateLights(): void {
    if (!streamer || !lightsDirty) return
    lightsDirty = false
    const list: LightSource[] = [], anchors: ShaftAnchor[] = []
    for (const slot of streamer.slots.values()) {
      for (const l of slot.data.lights) list.push(l)
      for (const a of slot.data.anchors) anchors.push(a)
    }
    lights.setSources(list)
    sceneLight.setSources(list)
    shafts.setAnchors(anchors)
  }

  /** Infinite maps, per frame after streaming: world-chunk prefetch ring ahead of the player (only when nothing
   * visible waits), heights / climate uploads and the periodic release of far blocks and provider chunks. */
  function infiniteFrame(dt: number, q: QualityPreset): void {
    const s = sampler
    if (!s || !map?.infinite || !streamer) return
    const st = streamer.stats
    if (st.pending === 0 || st.buildMs < S.budgetMs * 0.5) {
      const t0 = performance.now()
      const n = s.prefetch(rig.target.x, rig.target.z, q.viewRadius + S.keepMargin + IS.prefetchMargin, focusVel.x, focusVel.y,
        IS.prefetchPerFrame, t0 + IS.prefetchBudgetMs)
      if (n) { gen.prefetched += n; gen.lastMs = performance.now() - t0; gen.maxMs = Math.max(gen.maxMs, gen.lastMs) }
    }
    heights?.flush()
    climate?.flush()
    retainT -= dt
    if (retainT <= 0) {
      retainT = IS.retainSeconds
      const t0 = performance.now()
      s.retain(rig.target.x, rig.target.z, q.viewRadius + S.keepMargin + IS.blockMargin, IS.providerRadius)
      gen.retainMs = Math.max(gen.retainMs, performance.now() - t0)
    }
  }

  function clearMap(): void {
    questTrail.set([], () => 0)
    grass.clearTrample()
    footsteps.setEnv(null)
    reflections.setEnv(null)
    leaves.reset()
    leaves.setCanopies([])
    streamer?.clear()
    streamer = null
    props.clear()
    for (const f of fields.values()) { scene.remove(f.points); f.dispose() }
    fields.clear()
    heights?.dispose()
    heights = null
    climate?.dispose()
    climate = null
    bindClimate(null, false)
    lights.setSources([])
    sceneLight.setSources([])
    shafts.setAnchors([])
  }

  function roomBounds(m: GameMap, s: TerrainSampler): CameraBounds {
    let minX = Infinity, maxX = -Infinity, minZ = Infinity, maxZ = -Infinity
    for (let y = 0; y < m.height; y++) for (let x = 0; x < m.width; x++) {
      if (s.isVoid(x, y)) continue
      minX = Math.min(minX, x); maxX = Math.max(maxX, x); minZ = Math.min(minZ, y); maxZ = Math.max(maxZ, y)
    }
    if (!Number.isFinite(minX)) return { minX: 0, maxX: m.width, minZ: 0, maxZ: m.height }
    return { minX, maxX: maxX + 1, minZ, maxZ: maxZ + 1 }
  }

  function field(kind: string): ParticleField | null {
    let f = fields.get(kind)
    if (f) return f
    const def = RENDER.particles[kind]
    if (!def) return null
    // leaves / petals are simulated per leaf (leaves.ts) while the quality tier allows it
    if (RENDER.leaves.kinds[kind] && (RENDER.physics.tiers[settings().quality]?.leaves ?? 0) > 0) return null
    f = createParticleField(kind, def, heights?.texture ?? null, mapSize, fieldScale, heights?.wrap ?? false)
    f.target = 0
    fields.set(kind, f)
    scene.add(f.points)
    return f
  }

  function syncAspect(): void {
    if (!ext) return
    const aspect = ext.internal.width / ext.internal.height
    if (Math.abs(camera.aspect - aspect) > 1e-4) { camera.aspect = aspect; camera.updateProjectionMatrix() }
  }

  function applySettingsChange(): void {
    const q = quality()
    // the light field replaces the PointLight pool on the tiers that have it
    const pool = lightingTier(settings().quality).fieldLights > 0 ? 0 : Math.min(CONTENT.config.render.maxPointLights, q.pointLights)
    if (pool !== poolSize) { poolSize = pool; lights.setPoolSize(pool); lightsDirty = true }
    let rebuild = props.setNatureVariants(q.natureVariants)
    if (Math.round(q.grassPerTile) !== builtGrassPerTile) { builtGrassPerTile = Math.round(q.grassPerTile); rebuild = true }
    if (q.decorDensity !== builtDecor) { builtDecor = q.decorDensity; rebuild = true }
    if (q.terrainFringe !== builtFringe) { builtFringe = q.terrainFringe; rebuild = true }
    // content changes rebuild every chunk; the visible ones come back first under the catch-up budget
    if (rebuild && streamer) streamer.clear()
    bindClimate(climate, q.snowDust)
    if (q.particleScale !== fieldScale) {
      fieldScale = q.particleScale
      for (const f of fields.values()) { scene.remove(f.points); f.dispose() }
      fields.clear()
    }
  }
  const unsubscribe = ext?.onSettingsChanged(() => applySettingsChange())
  applySettingsChange()

  // --- lighting composition -------------------------------------------------
  const lightState = (): { s: LightingState; dir: Vec3; fade: number; moon: boolean } => {
    const preset = staticPreset()
    if (preset) return { s: { ...preset }, dir: dirFromAngles(preset.sunElevationDeg, preset.sunAzimuthDeg), fade: 1, moon: false }
    const sun = sunState(minutes)
    return { s: sampleLighting(minutes), dir: sun.dir, fade: sun.fade, moon: sun.moon }
  }

  /** Applies active weather grades (blended by their fade levels) onto a lighting state. */
  function applyWeather(s: LightingState): { sunMul: number; wind: number; aurora: number; ambient: number; wet: number } {
    let sunMul = 1, wind = 1, auroraLevel = 0, ambient = 1, wet = 0
    for (const [kind, level] of weatherLevels) {
      const def = RENDER.weather[kind]
      if (!def || level <= 0.001) continue
      const g = def.grade
      const w = level
      const mix = (base: number, mul: number | undefined) => base * (1 + ((mul ?? 1) - 1) * w)
      s.exposure = mix(s.exposure, g.exposure)
      s.saturation = mix(s.saturation, g.saturation)
      s.contrast = mix(s.contrast, g.contrast)
      s.fogNear = mix(s.fogNear, g.fogNear)
      s.fogFar = mix(s.fogFar, g.fogFar)
      s.hemiIntensity = mix(s.hemiIntensity, g.hemi)
      s.bloomStrength = mix(s.bloomStrength, g.bloomStrength)
      s.cloud = mix(s.cloud, g.cloud)
      s.shaft = mix(s.shaft, g.shaft)
      s.rim = mix(s.rim, g.rim)
      s.split = mix(s.split, g.split)
      if (g.wet !== undefined) wet = Math.max(wet, g.wet * w)
      if (g.warmth !== undefined) s.warmth += g.warmth * w
      if (g.vignette !== undefined) s.vignette += g.vignette * w
      if (g.lamps !== undefined) s.lamps = Math.max(s.lamps, g.lamps * w)
      if (g.tint && g.tintAmount) {
        const t = g.tintAmount * w
        s.fog = lerpHex(s.fog, g.tint, t)
        s.skyHorizon = lerpHex(s.skyHorizon, g.tint, t)
        s.skyBottom = lerpHex(s.skyBottom, g.tint, t)
        s.hemiSky = lerpHex(s.hemiSky, g.tint, t * 0.5)
      }
      sunMul *= 1 + ((g.sun ?? 1) - 1) * w
      wind = Math.max(wind, 1 + ((def.wind ?? 1) - 1) * w)
      if (def.aurora) auroraLevel = Math.max(auroraLevel, w)
      ambient *= 1 + ((def.ambientScale ?? 1) - 1) * w
    }
    return { sunMul, wind, aurora: auroraLevel, ambient, wet }
  }

  const _v = new THREE.Vector3()
  const _head = new THREE.Vector3()
  const _foot = new THREE.Vector3()
  /** Per-frame screen footprint of each live actor (name-tag overlap test); entries are reused. */
  const covers: (SpriteFootprint & { e: ActorEntry })[] = []
  /** '#rrggbb' split-tone colour -> luminance-neutral RGB multipliers (#808080 = no tint): the tint shifts hue only. */
  const tint = (hex: string, out: Vec3 = [1, 1, 1]): Vec3 => {
    const c = hexToRgb(hex)
    const luma = Math.max(1e-3, 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2])
    out[0] = c[0] / luma; out[1] = c[1] / luma; out[2] = c[2] / luma
    return out
  }

  const view: WorldViewExt = {
    scene,
    camera,
    get map() { return map },
    get streaming() { return streamer?.stats ?? null },
    get loadMs() { return loadMs },
    get worldGen() { return map?.infinite ? { ...gen } : null },
    get compileTimeouts() { return compileTimeouts },
    get lightDebug() {
      return {
        fieldLights: sceneLightUniforms.uApLfCount.value, sources: sceneLight.sourceCount, cloud: sceneLightUniforms.uApCloud.value.x,
        wet: sceneLightUniforms.uApWet.value.x, shafts: shafts.shown, lamps: debugLamps,
      }
    },

    invalidateMap() {
      if (!map || !sampler) return
      sampler.invalidate()
      streamer?.clear()
    },

    async loadMap(m, opts) {
      const t0 = performance.now()
      clearMap()
      map = m
      const preset = m.kind === 'cave' || m.kind === 'interior' || !m.outdoor
      const s = createTerrainSampler(m)
      sampler = s
      const infinite = !!m.infinite
      if (infinite) {
        // the spawn's world chunks first, so the first frame and the height window have data
        const sx = m.spawn.x, sy = m.spawn.y, r = S.prefillRadius + IS.ensureMargin
        s.ensure({ x0: sx - r, y0: sy - r, x1: sx + r, y1: sy + r }, Infinity)
      }
      maxTop = s.maxTop
      climate = createClimate(m, RENDER.fields, s)
      bindClimate(climate, quality().snowDust)
      heights = createHeightField(s, IS.heightWindow)
      mapSize.copy(heights.size)
      footsteps.setEnv({
        terrainKey: (tx, ty) => s.terrain(tx, ty)?.key ?? null,
        isLiquid: (tx, ty) => s.isLiquid(tx, ty),
        liquidY: (tx, ty) => s.liquidY(tx, ty),
        groundY: (x, z) => sampleWalkHeight(s, x, z),
        snowAt: (x, z) => climate?.sample('snow', x, z) ?? 0,
      })
      reflections.setEnv({ waterY: (tx, ty) => (s.isLiquid(tx, ty) ? s.liquidY(tx, ty) : null), heights })
      leaves.setGround(
        (x, z) => (s.isLiquid(Math.floor(x), Math.floor(z)) ? s.liquidY(Math.floor(x), Math.floor(z)) : sampleWalkHeight(s, x, z)),
        (x, z) => s.isLiquid(Math.floor(x), Math.floor(z)),
      )
      gen.prefetched = 0; gen.ensured = 0; gen.lastMs = 0; gen.maxMs = 0; gen.retainMs = 0
      retainT = IS.retainSeconds
      decor.setMap(m)
      opts?.onProgress?.(0.1)
      await props.prepare(m, climate, chunkSize, s)
      opts?.onProgress?.(0.3)
      streamer = newStreamer(m, s)
      rig.setBounds(preset ? roomBounds(m, s) : infinite ? null : { minX: 0, maxX: m.width, minZ: 0, maxZ: m.height }, preset)
      focus.set(m.spawn.x + 0.5, sampleWalkHeight(s, m.spawn.x + 0.5, m.spawn.y + 0.5), m.spawn.y + 0.5)
      lastFocus.copy(focus)
      focusVel.set(0, 0)
      syncAspect()
      rig.snap(focus)
      // build what the first frame shows (camera frustum + a small ring); the rest streams in during play
      const frame = streamFrame(quality())
      let first = -1
      for (;;) {
        const left = streamer.prefill(frame, S.prefillRadius, performance.now() + 12)
        if (first < 0) first = left + 1
        opts?.onProgress?.(0.3 + 0.68 * (1 - left / Math.max(1, first)))
        if (left === 0) break
        await yieldFrame()
      }
      await Promise.all(compileFinished(STAGE_COUNT))
      updateLights()
      weatherLevels.clear()
      snapAmbience = true
      loadMs = performance.now() - t0
      opts?.onProgress?.(1)
    },

    update(dtSec, f, minutesOfDay) {
      const dt = Math.max(0, Math.min(dtSec, 0.25))
      time += dt
      minutes = minutesOfDay
      const q = quality()
      const st = settings()
      focus.set(f.x, f.elev, f.y)
      if (dt > 0) {
        const vx = (focus.x - lastFocus.x) / dt, vz = (focus.z - lastFocus.z) / dt
        const k = 1 - Math.exp(-dt * 4)
        if (Math.hypot(vx, vz) < 60) focusVel.set(focusVel.x + (vx - focusVel.x) * k, focusVel.y + (vz - focusVel.y) * k)
        else focusVel.set(0, 0)
      }
      lastFocus.copy(focus)
      syncAspect()
      rig.update(dt, focus)
      yaw.value = cameraYaw(camera)
      camera.updateMatrixWorld()
      setOcclusionView(f.x, f.elev, f.y, camera)

      // weather fade levels (outdoor only)
      const outdoor = !staticPreset()
      const snap = snapAmbience
      snapAmbience = false
      const fade = snap ? 1 : 1 - Math.exp(-dt * 3 / Math.max(0.05, RENDER.weatherFadeSeconds))
      const kinds = new Set([...weatherLevels.keys(), weatherTarget.kind])
      for (const k of kinds) {
        const target = outdoor && k === weatherTarget.kind && k !== 'clear' ? weatherTarget.intensity : 0
        const cur = weatherLevels.get(k) ?? 0
        const next = cur + (target - cur) * fade
        if (next < 0.001 && target === 0) weatherLevels.delete(k)
        else weatherLevels.set(k, next)
      }

      const { s, dir, fade: sunFade, moon } = lightState()
      // time-of-day night factor before weather raises the lamps (night-only particles follow the clock, not the clouds)
      const night = s.lamps
      debugLamps = s.lamps
      const wx = applyWeather(s)
      sky.apply(s, dir, sunFade * wx.sunMul, rig.target, camera, rig.distance, time)
      const shadowsOn = st.shadows && q.shadows
      sky.setShadows(shadowsOn, Math.round(CONTENT.config.render.shadowMapSize * q.shadowMapScale), q.shadowRadius)
      const cast = shadowsOn && q.propShadows
      props.setShadows(cast)
      if (cast !== shadowsCast) {
        shadowsCast = cast
        if (streamer) for (const slot of streamer.slots.values()) if (slot.data.props) props.applyShadows(slot.data.props)
      }
      props.setLamps(s.lamps)

      const pxPerUnit = (ext?.internal.height ?? renderer.canvas.height) / (2 * Math.tan(THREE.MathUtils.degToRad(camera.fov) / 2))
      lights.update(dt, time, focus, s.lamps, q.glowSprites, pxPerUnit)
      // light field (lamps, windows, fires), cloud shadows and wet ground: shared uniforms of every lit material
      const lightTier = lightingTier(st.quality)
      sceneLight.update({ dt, time, focus, quality: st.quality, state: s, wet: wx.wet, wind: wx.wind, sky: sky.hemi.color, outdoor })
      updateSpriteShadows({ dir, light: sky.sun.intensity, moon, outdoor, cast: shadowsOn && lightTier.spriteCast })
      updateSpriteLighting({
        dir, sunColor: sky.sun.color, sunMul: sunFade, state: s, rim: 1, quality: st.quality, camera,
        shadowUv: 1 / (sky.sun.shadow.camera.right - sky.sun.shadow.camera.left), shadows: shadowsOn, outdoor,
      })
      shafts.update({
        dt, time, focus, count: outdoor ? lightTier.shafts : 0, dir, color: sky.sun.color, moon,
        strength: s.shaft * (moon ? RENDER.lighting.shafts.moon : 1) * sunFade,
      })
      liquids.update(time, sky.ambientLight, q.waterSparkles)
      updateWind(time, wx.wind)

      // chunk streaming around the camera target: build within budget, evict far chunks, show wanted ones
      if (streamer) {
        camera.updateMatrixWorld()
        streamer.update(streamFrame(q))
        compileFinished(STAGE_COUNT)
        for (const slot of streamer.slots.values()) slot.data.group.visible = slot.wanted && slot.data.ready
        updateLights()
        infiniteFrame(dt, q)
      }

      const benders: GrassBender[] = []
      for (const e of registry) if (e.isVisible() && e.bendRadius > 0) {
        const p = e.object.position
        benders.push({ x: p.x, y: p.y, z: p.z, r: e.bendRadius })
      }
      benders.sort((a, b) => (a.x - focus.x) ** 2 + (a.z - focus.z) ** 2 - ((b.x - focus.x) ** 2 + (b.z - focus.z) ** 2))
      const tier = RENDER.physics.tiers[st.quality] ?? RENDER.physics.tiers.medium
      if (st.quality !== physicsTier) {
        physicsTier = st.quality
        footsteps.configure(tier)
        if (tier.leaves > 0) for (const k of Object.keys(RENDER.leaves.kinds)) { const old = fields.get(k); if (old) { scene.remove(old.points); old.dispose(); fields.delete(k) } }
      }
      if (tier.trample) {
        const lh = CONTENT.config.world.levelHeight * 1.5
        grass.updateTrample(dt, focus.x, focus.z, benders, (x, z, y) => !sampler || Math.abs(sampleWalkHeight(sampler, x, z) - y) < lh)
      } else {
        grass.clearTrample()
        grass.setBenders(benders)
      }

      leaves.setLimit(tier.leaves)
      canopyT -= dt
      if (canopyT <= 0 && streamer) {
        canopyT = 0.4
        const near: Canopy[] = []
        for (const slot of streamer.slots.values()) {
          const list = slot.data.props?.canopies
          if (!list?.length) continue
          for (const c of list) if (Math.hypot(c.x - focus.x, c.z - focus.z) < RENDER.leaves.reach) near.push(c)
        }
        leaves.setCanopies(near)
      }

      stepList.length = 0
      for (const e of registry) {
        let a = stepActors.get(e)
        if (!a) { a = { id: e, x: 0, y: 0, z: 0, visible: true, kind: e.stepKind, scale: e.stepScale }; stepActors.set(e, a) }
        const p = e.object.position
        a.x = p.x; a.y = p.y; a.z = p.z
        a.visible = e.isVisible()
        stepList.push(a)
      }

      atlasT -= dt
      if (atlasT <= 0) { atlasT = 0.5; if (atlas.refresh()) grass.refresh() }

      // particles: ambient set by biome (or interior/cave preset) + active weather kinds
      const wanted = new Map<string, number>()
      if (map) {
        const preset = staticPreset()
        const ambient = preset ? preset.ambient : sampler?.biome(tileOf(f.x), tileOf(f.y))?.ambient ?? []
        for (const a of ambient) wanted.set(a, wx.ambient)
        for (const [k, lvl] of weatherLevels) for (const p of RENDER.weather[k]?.particles ?? []) wanted.set(p, Math.max(wanted.get(p) ?? 0, lvl))
      }
      for (const k of wanted.keys()) field(k)
      const leafLevels: Record<string, number> = {}
      for (const k of Object.keys(RENDER.leaves.kinds)) {
        const d = RENDER.particles[k]
        leafLevels[k] = (wanted.get(k) ?? 0) * (d?.time === 'night' ? night : d?.time === 'day' ? 1 - night : 1)
      }
      leaves.setLevels(leafLevels)
      const windVec = new THREE.Vector2(...RENDER.wind.dir).normalize().multiplyScalar(wx.wind)
      for (const [k, fl] of fields) {
        fl.target = wanted.get(k) ?? 0
        fl.impactOn = tier.impacts
        if (snap) fl.level = fl.target
        const def = RENDER.particles[k]
        const tf = def.time === 'night' ? night : def.time === 'day' ? 1 - night : 1
        fl.update(dt, time, focus, windVec, sky.ambientLight, tf, pxPerUnit)
        if (fl.target === 0 && fl.level < 0.002) { scene.remove(fl.points); fl.dispose(); fields.delete(k) }
      }
      aurora.update(time, camera, wx.aurora * (RENDER.aurora.nightOnly ? s.lamps : 1))
      leaves.update(dt, time, focus, sky.ambientLight)
      footsteps.update(dt, time, focus, stepList, sky.ambientLight, pxPerUnit)
      reflections.update(time, sky.ambientLight, focus, registry, tier.reflections && outdoor)
      liquids.setRipples(tier.ripples, weatherLevels.get('rain') ?? 0)
      {
        const C = RENDER.snowCover
        const snowing = weatherLevels.get(C.weather) ?? 0
        snowLevel = Math.min(1, Math.max(0, snowLevel + (snowing > 0.3 ? (dt / C.buildSec) * snowing : -dt / C.meltSec)))
        setSnowCover(tier.snowCover && outdoor ? snowLevel * C.max : 0)
      }
      fx.update(dt, time, camera, pxPerUnit)
      questTrail.update(time, reducedMotion.matches)

      post.exposure = s.exposure
      post.saturation = s.saturation
      post.contrast = s.contrast
      post.warmth = s.warmth
      post.bloomStrength = s.bloomStrength
      post.vignette = s.vignette
      post.split = lightTier.splitTone ? s.split : 0
      post.shadowTint = tint(s.shadowTint, post.shadowTint)
      post.highlightTint = tint(s.highlightTint, post.highlightTint)
    },

    setWeather(w) {
      weatherTarget.kind = RENDER.weather[w.kind] ? w.kind : 'clear'
      weatherTarget.intensity = Math.max(0, Math.min(1, w.intensity))
    },

    setZoom(level) { rig.setZoom(level) },

    createActor(opts: ActorOptions) { return createActorImpl(actorCtx, opts) },

    createCreatureActor(speciesId, shiny) { return createCreatureActorImpl(actorCtx, speciesId, shiny) },

    elevationAt(x, y) { return sampler ? sampleWalkHeight(sampler, x, y) : 0 },

    worldToScreen(x, elev, y) {
      _v.set(x, elev, y).project(camera)
      const w = renderer.canvas.clientWidth || renderer.canvas.width
      const h = renderer.canvas.clientHeight || renderer.canvas.height
      const visible = _v.z > -1 && _v.z < 1 && Math.abs(_v.x) <= 1.05 && Math.abs(_v.y) <= 1.05
      return { x: (_v.x * 0.5 + 0.5) * w, y: (0.5 - _v.y * 0.5) * h, visible }
    },

    spawnFx(kind, x, y, elev) { if (!footsteps.route(kind, x, elev, y)) fx.spawn(kind, x, elev, y) },

    setGroundItems(items) {
      // ground items are given as tile indices (GroundItemDef): orbs float over the tile centre
      const s = sampler
      fx.setGroundItems(items.map((i) => ({ id: i.id, x: i.x + 0.5, z: i.y + 0.5, y: s ? sampleWalkHeight(s, i.x + 0.5, i.y + 0.5) : 0 })))
    },

    setQuestPath(path) {
      questTrail.set(path, (x, y) => sampler ? sampleWalkHeight(sampler, x, y) : 0)
    },

    renderView(): RenderView {
      const showNames = settings().showNames
      const maxD = RENDER.overlay.maxDistance
      const pitch = cameraPitch(camera)
      let n = 0
      for (const e of registry) {
        e.head(_head, pitch)
        const sp = view.worldToScreen(_head.x, _head.y, _head.z)
        const near = _head.distanceTo(camera.position) < maxD
        const on = sp.visible && near && e.isVisible()
        e.tag.place(sp.x, sp.y, on, showNames)
        _foot.setFromMatrixPosition(e.object.matrixWorld)
        const c = (covers[n] ??= { e, x: 0, top: 0, bottom: 0, on: false })
        c.e = e; c.x = sp.x; c.top = sp.y; c.bottom = view.worldToScreen(_foot.x, _foot.y, _foot.z).y; c.on = on
        n++
      }
      // a name tag lying over another actor's sprite fades so that actor (the follower behind the player) stays readable
      for (let i = 0; i < n; i++) {
        const c = covers[i]
        const r = c.on ? c.e.tag.rect() : null
        c.e.tag.dim(!!r && tagOverSprite(r, covers, n, i, RENDER.overlay.coverHalfWidth))
      }
      return { scene, camera, focus, post }
    },

    dispose() {
      unsubscribe?.()
      clearMap()
      for (const e of [...registry]) e.object.removeFromParent()
      registry.clear()
      grass.dispose(); props.dispose(); decor.dispose(); fringe.dispose(); lights.dispose(); sceneLight.dispose(); shafts.dispose(); fx.dispose(); questTrail.dispose(); aurora.dispose(); sky.dispose()
      liquids.dispose(); footsteps.dispose(); leaves.dispose(); atlas.dispose(); matte.dispose(); glossy.dispose(); overlayLayer.dispose()
      map = null
      sampler = null
    },
  }
  return view
}
