#!/usr/bin/env bun
// Copies the game assets the promo uses (data/assets.json) from the game tree (read-only) into promo/public/,
// and extracts the game tables the promo needs into data/game.json. Never writes outside promo/.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const PROMO = path.resolve(import.meta.dir, '..');
const GAME = path.resolve(PROMO, '..');
const cfg = JSON.parse(readFileSync(path.join(PROMO, 'data/assets.json'), 'utf8'));

let n = 0;
for (const c of cfg.copy) {
  const src = path.join(GAME, c.from), dst = path.join(PROMO, c.to);
  mkdirSync(dst, { recursive: true });
  const files: string[] = c.files ?? readdirSync(src).filter((f) => f.endsWith(c.glob));
  for (const f of files) {
    if (!existsSync(path.join(src, f))) { console.warn(`missing: ${c.from}/${f}`); continue; }
    cpSync(path.join(src, f), path.join(dst, f));
    n++;
  }
}

const pick = (o: Record<string, unknown>, fields: string[]) => Object.fromEntries(fields.map((k) => [k, o[k]]));
const out: Record<string, unknown> = { _doc: 'Generated by scripts/sync-assets.ts from the game content tables. Do not edit by hand.' };
for (const [k, e] of Object.entries<any>(cfg.extract)) {
  const j = JSON.parse(readFileSync(path.join(GAME, e.from), 'utf8'));
  const list: Record<string, unknown>[] = e.key ? j[e.key] : j;
  out[k] = list.map((x) => pick(x, e.fields));
}
writeFileSync(path.join(PROMO, 'data/game.json'), JSON.stringify(out, null, 1));
console.log(`copied ${n} files; data/game.json: ${Object.entries(out).filter(([k]) => k !== '_doc').map(([k, v]) => `${k} ${(v as unknown[]).length}`).join(', ')}`);
