VENDOR = {
    "key": "anthropic",
    "name": "Anthropic",
    "nameZh": "Anthropic",
    "country": "US",
    "homepage": "https://www.anthropic.com",
    "officialModelListUrl": "https://platform.claude.com/docs/en/about-claude/models/overview",
    "changelogUrl": "https://www.anthropic.com/news",
    "notes": "Release dates cross-checked against the timeline page below plus OpenRouter/models.dev.",
}

TL = "https://hidekazu-konishi.com/entry/anthropic_claude_model_release_timeline.html"
FABLE = "https://www.anthropic.com/news/claude-fable-5-mythos-5"
FABLE_DOC = "https://platform.claude.com/docs/en/about-claude/models/introducing-claude-fable-5-and-claude-mythos-5"

LINES = [
    {
        "family": "claude-opus",
        "category": "llm",
        "src": [TL],
        "chain": [
            "claude1",
            "claude2",
            "claude21",
            "claude3opus",
            "claudeopus4",
            "claudeopus41",
            "claudeopus45",
            "claudeopus46",
            "claudeopus47",
            "claudeopus48",
            "claudeopus5",
            "claudeopus55",
        ],
    },
    {
        "family": "claude-sonnet",
        "category": "llm",
        "src": [TL],
        "chain": [
            "claude3sonnet",
            "claude35sonnet",
            "claude37sonnet",
            "claudesonnet4",
            "claudesonnet45",
            "claudesonnet46",
            "claudesonnet5",
            "claudesonnet55",
        ],
    },
    {
        "family": "claude-haiku",
        "category": "llm",
        "src": [TL],
        "chain": [
            "claudeinstant",
            "claude3haiku",
            "claude35haiku",
            "claudehaiku45",
            "claudehaiku55",
        ],
    },
    {
        "family": "claude-mythos",
        "category": "llm",
        "src": [FABLE],
        "chain": ["mythospreview", "claudemythos5", "claudemythos51"],
    },
    {
        "family": "claude-fable",
        "category": "llm",
        "src": [FABLE],
        "chain": ["mythospreview", "claudefable5", "claudefable51"],
    },
    {"family": "claude-code", "category": "code", "chain": ["claudecode"]},
    {"family": "claude-app", "category": "agent", "chain": ["claudecowork"]},
]

R = {
    "claude3haiku": {
        "displayName": "Claude 3 Haiku",
        "releaseDate": "2024-03-13",
        "sc": "secondary",
    },
    "claude35sonnet": {
        "displayName": "Claude 3.5 Sonnet",
        "releaseDate": "2024-06-20",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "notes": "An upgraded 'new' 3.5 Sonnet snapshot shipped 2024-10-22 under the same name.",
    },
    "claude37sonnet": {
        "displayName": "Claude 3.7 Sonnet",
        "releaseDate": "2025-02-24",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "notes": "First hybrid-reasoning Claude.",
    },
    "claudeopus4": {
        "displayName": "Claude Opus 4",
        "releaseDate": "2025-05-22",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudesonnet4": {
        "displayName": "Claude Sonnet 4",
        "releaseDate": "2025-05-22",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudeopus41": {
        "displayName": "Claude Opus 4.1",
        "releaseDate": "2025-08-05",
        "sc": "secondary",
        "sources": [TL],
        "status": "retired",
        "notes": "Retired 2026-08-05 per timeline page.",
    },
    "claudesonnet45": {
        "displayName": "Claude Sonnet 4.5",
        "releaseDate": "2025-09-29",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudehaiku45": {
        "displayName": "Claude Haiku 4.5",
        "releaseDate": "2025-10-15",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudeopus45": {
        "displayName": "Claude Opus 4.5",
        "releaseDate": "2025-11-24",
        "sc": "secondary",
        "sources": [TL],
        "notes": "Model id date 20251101 differs from the announcement date.",
    },
    "claudeopus46": {
        "displayName": "Claude Opus 4.6",
        "releaseDate": "2026-02-05",
        "sc": "secondary",
        "sources": [TL],
        "notes": "OpenRouter lists 2026-02-04.",
    },
    "claudesonnet46": {
        "displayName": "Claude Sonnet 4.6",
        "releaseDate": "2026-02-17",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudeopus47": {
        "displayName": "Claude Opus 4.7",
        "releaseDate": "2026-04-16",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudeopus48": {
        "displayName": "Claude Opus 4.8",
        "releaseDate": "2026-05-28",
        "sc": "secondary",
        "sources": [TL],
    },
    "claudefable5": {
        "displayName": "Claude Fable 5",
        "releaseDate": "2026-06-09",
        "sc": "official",
        "sources": [FABLE, FABLE_DOC],
        "parent": "mythospreview",
        "relation": "successor",
        "basis": "reported",
        "notes": "Same underlying model as Mythos 5 with all safeguards on; falls back to Opus 4.8 on high-risk topics. Suspended 2026-06-12 (US export controls), redeployed 2026-07-01. First public Mythos-class model.",
    },
    "claudemythos5": {
        "displayName": "Claude Mythos 5",
        "releaseDate": "2026-06-09",
        "sc": "official",
        "sources": [FABLE, FABLE_DOC],
        "parent": "mythospreview",
        "relation": "successor",
        "basis": "official",
        "notes": "Fable 5 without the cyber/bio classifiers; limited release via Project Glasswing. Succeeds Mythos Preview.",
    },
    "claudesonnet5": {
        "displayName": "Claude Sonnet 5",
        "releaseDate": "2026-06-30",
        "sc": "secondary",
        "sources": [TL],
        "notes": "models.dev lists 2026-06-29.",
    },
    "claudeopus5": {
        "displayName": "Claude Opus 5",
        "releaseDate": "2026-07-24",
        "sc": "secondary",
        "sources": [TL],
        "notes": "Described as close to Fable 5 intelligence at half the price.",
    },
    "claudefable51": {
        "displayName": "Claude Fable 5.1",
        "releaseDate": "2026-09-01",
        "sc": "secondary",
        "sources": [TL],
        "parent": "claudefable5",
        "relation": "successor",
        "basis": "official",
        "notes": "Released together with Mythos 5.1.",
    },
    "claudeopus55": {
        "displayName": "Claude Opus 5.5",
        "releaseDate": "2026-09-22",
        "sc": "secondary",
        "sources": [TL, "https://www.anthropic.com/claude-opus-5-5"],
        "notes": "First 5.5-family model; reported to match Fable 5.1 on most work at 40% lower cost.",
    },
    "claudesonnet55": {
        "displayName": "Claude Sonnet 5.5",
        "releaseDate": "2026-09-28",
        "notes": "Reported >30% faster than Sonnet 5 at the same price.",
    },
    "claudehaiku55": {
        "displayName": "Claude Haiku 5.5",
        "releaseDate": "2026-10-07",
        "notes": "Newest Claude as of 2026-10-09; OpenRouter/models.dev listings, no official page opened.",
    },
}

EXTRA = {
    "claude1": {
        "displayName": "Claude 1",
        "releaseDate": "2023-03-14",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "status": "retired",
        "notes": "API early access 2023-03-14.",
    },
    "claude2": {
        "displayName": "Claude 2",
        "releaseDate": "2023-07-11",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "status": "retired",
    },
    "claude21": {
        "displayName": "Claude 2.1",
        "releaseDate": "2023-11-21",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "status": "retired",
    },
    "claude3opus": {
        "displayName": "Claude 3 Opus",
        "releaseDate": "2024-03-04",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "status": "retired",
    },
    "claude3sonnet": {
        "displayName": "Claude 3 Sonnet",
        "releaseDate": "2024-03-04",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "status": "retired",
    },
    "claudeinstant": {
        "displayName": "Claude Instant",
        "releaseDate": "2023-03-14",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "status": "retired",
        "notes": "Retroactively the first Haiku-tier model.",
    },
    "claude35haiku": {
        "displayName": "Claude 3.5 Haiku",
        "releaseDate": "2024-11-04",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "notes": "Announced 2024-10-22; available 2024-11-04.",
    },
    "mythospreview": {
        "displayName": "Claude Mythos Preview",
        "releaseDate": "2026-04-07",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [
            "https://www.anthropic.com/claude/mythos",
            "https://en.wikipedia.org/wiki/Claude_Mythos",
            FABLE,
        ],
        "ow": False,
        "notes": "Announced 2026-04-07 as a restricted preview (Project Glasswing, cybersecurity). Root of the Mythos-class tier above Opus.",
    },
    "claudemythos51": {
        "displayName": "Claude Mythos 5.1",
        "releaseDate": "2026-09-01",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "parent": "claudemythos5",
        "relation": "successor",
        "basis": "official",
        "notes": "Restricted; released with Fable 5.1.",
    },
    "claudecode": {
        "displayName": "Claude Code",
        "releaseDate": "2025-02-24",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [TL],
        "ow": False,
        "catbasis": "agentic coding product",
        "notes": "Research preview with Claude 3.7 Sonnet 2025-02-24; GA with Claude 4 on 2025-05-22. Product, not a model.",
    },
    "claudecowork": {
        "displayName": "Claude Cowork",
        "releaseDate": "2026-01-12",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [
            "https://simonwillison.net/2026/Jan/12/claude-cowork/",
            "https://www.unite.ai/anthropic-folds-cowork-into-a-single-claude-experience-across-plans/",
        ],
        "ow": False,
        "catbasis": "desktop computer-agent product",
        "notes": "Research preview 2026-01-12, GA 2026-04-09; merged into the single Claude app announced 2026-09-16.",
    },
}

SPECIES = {
    "claude-haiku": "claudehaiku45",
    "claude-opus-4-8": "claudeopus48",
    "claude-opus": "claudeopus55",
    "claude-3-opus": "claude3opus",
    "claude-3-5-sonnet": "claude35sonnet",
    "claude-sonnet": "claudesonnet55",
    "claude-fable": "claudefable51",
    "claude-mythos-preview": "mythospreview",
    "claude-mythos": "claudemythos51",
    "claude-code": "claudecode",
    "claude-cowork": "claudecowork",
}

EXCLUDED = [
    "Dated snapshots (e.g. claude-sonnet-4-5-20250929, claude-3-5-sonnet-20241022): collapsed into base models.",
    "OpenRouter ':batch' and '~latest' aliases.",
]

GAPS = [
    "No official Anthropic page was fetched for the dated model list; dates for 2023-2026 models rely on the third-party timeline page plus OpenRouter/models.dev (cross-consistent).",
    "Claude 'Fable 5.5' is rumoured (leaks) but not announced as of 2026-10-05; not recorded.",
]
