VENDOR = {
    "key": "openai",
    "name": "OpenAI",
    "nameZh": "OpenAI",
    "country": "US",
    "homepage": "https://openai.com",
    "officialModelListUrl": "https://platform.openai.com/docs/models",
    "changelogUrl": "https://platform.openai.com/docs/changelog",
    "notes": "help.openai.com and platform docs returned HTTP 403 to automated fetch; dates come from models.dev/OpenRouter and secondary reporting.",
}

WIKI = "https://en.wikipedia.org/wiki/"
SRC_GPT6 = "https://www.macrumors.com/2026/09/22/openai-gpt-6-sol-luna/"
SRC_SORA = "https://en.wikipedia.org/wiki/Sora_(text-to-video_model)"

LINES = [
    {
        "family": "gpt",
        "category": "llm",
        "chain": [
            "gpt35",
            "gpt4",
            "gpt4turbo",
            "gpt4o",
            "gpt41",
            "gpt5",
            "gpt51",
            "gpt52",
            "gpt54",
            "gpt55",
            "gpt56sol",
            "gpt6sol",
            "gpt61sol",
        ],
    },
    {"family": "gpt-4-5", "category": "llm", "chain": ["gpt4o", "gpt45"]},
    {
        "family": "gpt-astra",
        "category": "llm",
        "chain": ["gpt56sol", "gpt6astra"],
        "tags": ["flagship"],
    },
    {"family": "gpt-terra", "category": "llm", "chain": ["gpt55", "gpt56terra"]},
    {
        "family": "gpt-luna",
        "category": "llm",
        "chain": ["gpt55", "gpt56luna", "gpt6luna"],
    },
    {
        "family": "gpt-mini",
        "category": "llm",
        "chain": ["gpt4omini", "gpt41mini", "gpt5mini", "gpt54mini"],
    },
    {
        "family": "gpt-nano",
        "category": "llm",
        "chain": ["gpt41nano", "gpt5nano", "gpt54nano"],
    },
    {
        "family": "o-series",
        "category": "reasoning",
        "chain": ["o1", "o3mini", "o3", "o4mini"],
    },
    {
        "family": "gpt-oss",
        "category": "llm",
        "chain": ["gptoss120b"],
        "tags": ["open-weights"],
    },
    {"family": "gpt-oss", "category": "llm", "chain": ["gptoss20b"]},
    {
        "family": "gpt-oss",
        "category": "llm",
        "chain": ["gptoss120b", "gptosssafeguard120b"],
        "relation": "post-train",
        "basis": "reported",
    },
    {
        "family": "gpt-oss",
        "category": "llm",
        "chain": ["gptoss20b", "gptosssafeguard20b"],
        "relation": "post-train",
        "basis": "reported",
    },
    {"family": "codex", "category": "code", "chain": ["codex2021"]},
    {
        "family": "codex",
        "category": "code",
        "chain": [
            "codex1",
            "gpt5codex",
            "gpt51codex",
            "gpt51codexmax",
            "gpt52codex",
            "gpt53codex",
            "gpt53codexspark",
        ],
    },
    {"family": "codex", "category": "code", "chain": ["gpt51codex", "gpt51codexmini"]},
    {
        "family": "gpt-image",
        "category": "image",
        "chain": [
            "dalle1",
            "dalle2",
            "dalle3",
            "gptimage1",
            "gptimage15",
            "gptimage2",
            "gptimage25sunburst",
        ],
    },
    {
        "family": "gpt-image",
        "category": "image",
        "chain": ["gptimage1", "gptimage1mini"],
    },
    {
        "family": "gpt-image",
        "category": "image",
        "chain": ["gptimage2", "gptimage25flare"],
    },
    {"family": "sora", "category": "video", "chain": ["sora1", "sora2"]},
    {
        "family": "whisper",
        "category": "speech-asr",
        "chain": ["whisperlargev3", "whisperlargev3turbo"],
        "relation": "distill",
        "basis": "reported",
    },
    {
        "family": "gpt-realtime",
        "category": "speech-tts",
        "chain": ["gptrealtime21", "gptlive1"],
    },
    {
        "family": "text-embedding",
        "category": "embedding",
        "chain": ["textembeddingada002", "textembedding3small", "textembedding3large"],
    },
    {"family": "chatgpt", "category": "agent", "chain": ["chatgptapp", "chatgptdots"]},
]

R = {
    "gpt4": {
        "displayName": "GPT-4",
        "releaseDate": "2023-03-14",
        "sc": "background",
        "sources": ["https://openai.com/index/gpt-4-research/"],
    },
    "gpt4turbo": {
        "displayName": "GPT-4 Turbo",
        "releaseDate": "2023-11-06",
        "notes": "DevDay 2023 preview; GA 2024-04-09 (OpenRouter listing date).",
    },
    "gpt4o": {"releaseDate": "2024-05-13", "sc": "background"},
    "gpt41": {
        "displayName": "GPT-4.1",
        "notes": "API-focused line parallel to GPT-4.5; chain parent kept at GPT-4o (series).",
        "parent": "gpt4o",
    },
    "gpt5": {
        "displayName": "GPT-5",
        "parent": "gpt41",
        "relation": "successor",
        "basis": "reported",
        "notes": "Unified system: replaces GPT-4o/4.1 and the o-series (o3) in ChatGPT. The reasoning side (o1->o3->o4-mini) is NOT a parent chain; both converge here.",
    },
    "gpt51": {"displayName": "GPT-5.1"},
    "gpt52": {
        "displayName": "GPT-5.2",
        "notes": "A GPT-5.2 Pro compute tier also exists (not recorded separately).",
    },
    "gpt54": {
        "displayName": "GPT-5.4",
        "notes": "GPT-5.4 Pro tier also exists; GPT-5.3 chat/instant builds are not recorded (replaced by 5.4).",
    },
    "gpt55": {
        "displayName": "GPT-5.5",
        "releaseDate": "2026-04-23",
        "releaseDateBasis": "catalog",
        "notes": "Codename Spud per reporting. GPT-5.5 Pro tier and GPT-5.5 Instant (2026-05-05) exist; OpenRouter lists 2026-04-24.",
    },
    "gpt56sol": {
        "displayName": "GPT-5.6 Sol",
        "notes": "GPT-5.6 launched with three tiers Sol / Terra / Luna on 2026-07-09 (each also has a Pro tier).",
    },
    "gpt56terra": {
        "displayName": "GPT-5.6 Terra",
        "notes": "Mid tier of GPT-5.6; no GPT-6 Terra announced as of 2026-09-23.",
        "status": "current",
    },
    "gpt56luna": {"displayName": "GPT-5.6 Luna", "status": "superseded"},
    "gpt6astra": {
        "displayName": "GPT-6 Astra",
        "releaseDate": "2026-09-04",
        "releaseDateBasis": "secondary",
        "sc": "secondary",
        "sources": ["https://www.lindy.ai/blog/gpt-6", SRC_GPT6],
        "notes": "Flagship, first GPT-6 model: approved users 2026-09-03, everyone 2026-09-04. Pro compute tier exists. Powers ChatGPT Dots. Parent kept at GPT-5.6 Sol as series successor (no official weights lineage).",
    },
    "gpt6sol": {
        "displayName": "GPT-6 Sol",
        "releaseDate": "2026-09-22",
        "sc": "secondary",
        "sources": [SRC_GPT6],
        "notes": "Trained with methods similar to Astra (reported); cheaper tier. Pro tier exists.",
    },
    "gpt6luna": {
        "displayName": "GPT-6 Luna",
        "releaseDate": "2026-09-22",
        "sc": "secondary",
        "sources": [SRC_GPT6],
        "notes": "Fast/high-volume tier; default for Free/Go in the ChatGPT desktop app.",
    },
    "gpt61sol": {
        "displayName": "GPT-6.1 Sol",
        "releaseDate": "2026-09-29",
        "sc": "secondary",
        "sources": ["https://www.lindy.ai/blog/gpt-6"],
        "notes": "GPT-6.1 Astra reportedly on hold.",
    },
    "gpt4omini": {
        "displayName": "GPT-4o mini",
        "releaseDate": "2024-07-18",
        "sc": "background",
    },
    "gpt41mini": {"displayName": "GPT-4.1 mini"},
    "gpt41nano": {"displayName": "GPT-4.1 nano"},
    "gpt5mini": {"displayName": "GPT-5 mini"},
    "gpt5nano": {"displayName": "GPT-5 nano"},
    "gpt54mini": {"displayName": "GPT-5.4 mini", "releaseDate": "2026-03-17"},
    "gpt54nano": {"displayName": "GPT-5.4 nano"},
    "o1": {
        "displayName": "o1",
        "releaseDate": "2024-12-05",
        "sc": "background",
        "catbasis": "official: dedicated reasoning model (o-series)",
    },
    "o3mini": {
        "displayName": "o3-mini",
        "releaseDate": "2025-01-31",
        "releaseDateBasis": "catalog",
        "notes": "models.dev date 2024-12-20 is the o3 announcement; availability 2025-01-31.",
    },
    "o3": {
        "displayName": "o3",
        "parent": "o3mini",
        "notes": "o3 preview announced 2024-12-20; released 2025-04-16. o3-pro 2025-06-10 also exists.",
    },
    "o4mini": {"displayName": "o4-mini"},
    "gptoss120b": {"displayName": "gpt-oss-120b", "ow": True},
    "gptoss20b": {"displayName": "gpt-oss-20b", "ow": True},
    "gptosssafeguard120b": {
        "displayName": "gpt-oss-safeguard-120b",
        "ow": True,
        "tags": ["safety"],
        "notes": "Safety-classifier fine-tune of gpt-oss; kept as a lineage example, low notability.",
    },
    "gptosssafeguard20b": {
        "displayName": "gpt-oss-safeguard-20b",
        "ow": True,
        "tags": ["safety"],
    },
    "codex2021": {
        "displayName": "OpenAI Codex (2021)",
        "releaseDate": "2021-08-10",
        "sc": "background",
        "sources": ["https://openai.com/index/openai-codex/"],
        "notes": "GPT-3 descendant powering GitHub Copilot; API private beta 2021-08-10. Name-sake only: no weights relation to the 2025 Codex models.",
    },
    "gpt5codex": {
        "displayName": "GPT-5-Codex",
        "parent": "codex1",
        "notes": "Date from models.dev/OpenRouter.",
    },
    "gpt51codex": {"displayName": "GPT-5.1-Codex"},
    "gpt51codexmax": {
        "displayName": "GPT-5.1-Codex-Max",
        "releaseDate": "2025-11-19",
        "sc": "background",
        "releaseDateBasis": "background",
        "notes": "Catalog dates (2025-11-13 models.dev / 2025-12-04 OpenRouter) are the base model / API listing dates; announcement date from memory.",
    },
    "gpt51codexmini": {"displayName": "GPT-5.1-Codex-Mini"},
    "gpt52codex": {
        "displayName": "GPT-5.2-Codex",
        "notes": "Announced 2025-12-18, API 2026-01-14 (OpenRouter); models.dev says 2025-12-11.",
    },
    "gpt53codex": {"displayName": "GPT-5.3-Codex"},
    "gpt53codexspark": {
        "displayName": "GPT-5.3-Codex-Spark",
        "parent": "gpt53codex",
        "notes": "Low-latency variant (Cerebras-served); keep: marketed as a separate model.",
    },
    "dalle1": {
        "displayName": "DALL-E",
        "releaseDate": "2021-01-05",
        "sc": "background",
        "sources": ["https://openai.com/index/dall-e/"],
        "catbasis": "official: text-to-image",
    },
    "dalle2": {
        "displayName": "DALL-E 2",
        "releaseDate": "2022-04-06",
        "sc": "background",
        "sources": ["https://openai.com/index/dall-e-2/"],
    },
    "dalle3": {
        "displayName": "DALL-E 3",
        "releaseDate": "2023-09-20",
        "sc": "background",
        "sources": ["https://openai.com/index/dall-e-3/"],
    },
    "gptimage1": {
        "displayName": "GPT Image 1",
        "releaseDate": "2025-04-23",
        "releaseDateBasis": "catalog",
        "notes": "ChatGPT 4o image generation 2025-03-25 (roster date); API gpt-image-1 2025-04-23/24.",
    },
    "gptimage1mini": {"displayName": "GPT Image 1 mini"},
    "gptimage15": {"displayName": "GPT Image 1.5"},
    "gptimage2": {
        "displayName": "GPT Image 2",
        "notes": "Adds a reasoning model to image generation (reported).",
    },
    "gptimage25sunburst": {
        "displayName": "GPT Image 2.5 Sunburst",
        "releaseDate": "2026-09-08",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [
            "https://www.atlabs.ai/blog/gpt-image-2.5-prompt-guide-2026-flare-vs-sunburst-quality-steps-and-consistent-characters"
        ],
        "notes": "Larger quality-focused tier; sibling of Flare, released together.",
    },
    "gptimage25flare": {
        "displayName": "GPT Image 2.5 Flare",
        "releaseDate": "2026-09-08",
        "sc": "secondary",
        "releaseDateBasis": "secondary",
        "sources": [
            "https://www.atlabs.ai/blog/gpt-image-2.5-prompt-guide-2026-flare-vs-sunburst-quality-steps-and-consistent-characters"
        ],
        "notes": "Small speed-focused tier (50% lower latency than GPT Image 2, reported).",
    },
    "sora1": {
        "displayName": "Sora",
        "releaseDate": "2024-12-09",
        "sc": "background",
        "sources": ["https://openai.com/index/sora-is-here/", SRC_SORA],
        "status": "retired",
        "notes": "Announced 2024-02-15; public release 2024-12-09.",
        "catbasis": "official: text-to-video",
    },
    "sora2": {
        "displayName": "Sora 2",
        "releaseDate": "2025-09-30",
        "sc": "official",
        "sources": ["https://openai.com/index/sora-2/", SRC_SORA],
        "status": "retired",
        "notes": "RETIRED: OpenAI announced 2026-03-24 it is discontinuing Sora; app/web closed 2026-04-26; API (sora-2, sora-2-pro) removed 2026-09-24.",
    },
    "whisperlargev3": {
        "displayName": "Whisper large-v3",
        "releaseDate": "2023-11-06",
        "sc": "background",
        "sources": ["https://github.com/openai/whisper"],
        "ow": True,
        "parent": None,
        "catbasis": "official: speech recognition",
    },
    "whisperlargev3turbo": {
        "displayName": "Whisper large-v3-turbo",
        "releaseDate": "2024-10-01",
        "ow": True,
        "notes": "Pruned/fine-tuned large-v3 (reported by OpenAI repo).",
    },
    "gptrealtime21": {
        "displayName": "gpt-realtime-2.1",
        "releaseDate": "2026-07-06",
        "sc": "secondary",
        "sources": [
            "https://community.openai.com/t/new-realtime-models-on-the-api-gpt-realtime-2-1-and-gpt-realtime-2-1-mini/1385896"
        ],
        "catbasis": "speech-to-speech realtime model",
        "notes": "Mini variant released together; gpt-realtime retired 2027-01-20 per reporting.",
    },
    "textembeddingada002": {"displayName": "text-embedding-ada-002"},
    "textembedding3small": {"displayName": "text-embedding-3-small"},
    "textembedding3large": {"displayName": "text-embedding-3-large", "parent": "textembeddingada002"},
}

EXTRA = {
    "gpt35": {
        "displayName": "GPT-3.5",
        "releaseDate": "2022-11-30",
        "sc": "background",
        "sources": ["https://openai.com/index/chatgpt/"],
        "notes": "GPT-3.5 series powered the ChatGPT research preview (2022-11-30); gpt-3.5-turbo API 2023-03-01.",
        "ow": False,
    },
    "gpt45": {
        "displayName": "GPT-4.5",
        "releaseDate": "2025-02-27",
        "sc": "background",
        "sources": ["https://en.wikipedia.org/wiki/GPT-4.5"],
        "notes": "Research preview; OpenAI called it its last non-reasoning model; deprecated.",
        "status": "deprecated",
        "ow": False,
    },
    "codex1": {
        "displayName": "codex-1",
        "releaseDate": "2025-05-16",
        "sc": "background",
        "sources": ["https://openai.com/index/introducing-codex/"],
        "parent": "o3",
        "relation": "post-train",
        "basis": "official",
        "notes": "Model behind the Codex cloud agent: a version of o3 optimized for software engineering (official). Chain via the Codex family continues from here.",
        "ow": False,
    },
    "gptlive1": {
        "displayName": "GPT-Live-1",
        "releaseDate": "2026-09-10",
        "sc": "official",
        "sources": [
            "https://openai.com/index/introducing-gpt-live-1-in-the-api/",
            "https://www.mindstudio.ai/blog/what-is-gpt-live-1-openai-voice-model",
        ],
        "catbasis": "full-duplex speech-to-speech voice model; delegates reasoning to a backend model",
        "notes": "In ChatGPT voice from ~2026-07-08, API 2026-09-10 (reported). Not a replacement for the Realtime API.",
        "ow": False,
    },
    "chatgptapp": {
        "displayName": "ChatGPT",
        "releaseDate": "2022-11-30",
        "sc": "background",
        "sources": ["https://openai.com/index/chatgpt/"],
        "catbasis": "consumer assistant product",
        "notes": "Product, not a model.",
        "ow": False,
    },
    "chatgptdots": {
        "displayName": "ChatGPT Dots",
        "releaseDate": "2026-09-29",
        "sc": "secondary",
        "sources": [
            "https://techcrunch.com/2026/09/29/openai-launches-dots-its-bubbly-agentic-avatar/",
            "https://www.tomsguide.com/ai/openai-gave-chatgpt-a-virtual-computer-to-run-errands-for-you",
        ],
        "catbasis": "always-on cloud agent product on GPT-6 Astra",
        "notes": "Successor to ChatGPT agent (removed from ChatGPT early Aug 2026). Runs on GPT-6 Astra.",
        "ow": False,
    },
}

SPECIES = {
    "gpt-35": "gpt35",
    "gpt-4": "gpt4",
    "gpt-4o": "gpt4o",
    "chatgpt": "chatgptapp",
    "o1": "o1",
    "gpt-5": "gpt5",
    "gpt-6-astra": "gpt6astra",
    "gpt-5-5": "gpt55",
    "gpt-5-6": "gpt56sol",
    "gpt-6-luna": "gpt6luna",
    "gpt-6-sol": "gpt61sol",
    "codex-2021": "codex2021",
    "openai-codex": "codex1",
    "gpt-oss": "gptoss120b",
    "dall-e": "dalle1",
    "gpt-image-1": "gptimage1",
    "gpt-image-2-5": "gptimage25sunburst",
    "sora-2": "sora2",
    "chatgpt-dots": "chatgptdots",
}

IGNORE = {
    "gpt35turbo",
    "gpt35turbo16k",
    "gpt35turboinstruct",
    "o3minihigh",
    "o1pro",
    "o4minihigh",
    "o3pro",
    "gpt5pro",
    "gpt5image",
    "gpt5imagemini",
    "gpt52chat",
    "gpt52pro",
    "gpt54pro",
    "gpt55pro",
    "gpt54image2",
    "gpt55instant",
    "gptaudio",
    "gptaudiomini",
    "gptrealtimewhisper",
    "gpt56lunapro",
    "gpt56solpro",
    "gpt56terrapro",
    "gpt6astrafast",
    "gpt6astrapro",
    "gpt6lunapro",
    "gpt6solpro",
    "gpt61solpro",
}

EXCLUDED = [
    "Pro compute tiers (o1-pro, o3-pro, GPT-5/5.2/5.4/5.5 Pro, GPT-5.6 and GPT-6 Sol/Luna/Terra/Astra Pro): same weights family, higher compute; noted on base models only.",
    "OpenRouter-only wrappers: GPT-5 Image(/Mini), GPT-5.4 Image 2, GPT-5.2 Chat, GPT-Audio(-Mini), GPT-6 Astra (Fast): serving SKUs.",
    "Dated snapshots of GPT-3.5 Turbo / GPT-4o: collapsed into base models.",
    "gpt-realtime-whisper (2026-05-07, models.dev): ASR sub-model of the realtime stack; date unverified.",
]

GAPS = [
    "OpenAI help-center and platform docs return HTTP 403 to automated fetch: GPT-5.x-6.x dates rely on models.dev/OpenRouter plus secondary reporting (MacRumors, Lindy, TechCrunch).",
    "GPT-5.3 Codex Spark / GPT-5.5 Instant / GPT-5.4 mini exact official dates not confirmed.",
    "GPT-5.1-Codex-Max announcement date from memory (2025-11-19), not re-verified this session.",
]
