#!/usr/bin/env python3
"""Regenerate the matrix + per-type summary in docs/typechart.md from content/types.json.

Only the block between the BEGIN/END markers is rewritten; the hand-written rationale stays untouched.
Usage: python3 tools/data/typechart_md.py [--check]   (--check exits 1 if the doc is stale)
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DOC = ROOT / 'docs' / 'typechart.md'
BEGIN, END = '<!-- typechart:begin (generated by tools/data/typechart_md.py) -->', '<!-- typechart:end -->'
CELL = {2: '**2**', 0.5: '½', 0: '0', 1: '·'}


def render(data):
    types = data['types']
    ids = [t['id'] for t in types]
    name = {t['id']: t['nameZh'] for t in types}
    chart = data['chart']
    m = lambda a, d: chart.get(a, {}).get(d, 1)
    out = ['攻击方（行）→ 防守方（列）。**2** = 效果绝佳，½ = 效果不好，0 = 无效，· = 普通。', '']
    out.append('| 攻 \\ 防 | ' + ' | '.join(name[d] for d in ids) + ' |')
    out.append('|---|' + '---|' * len(ids))
    for a in ids:
        out.append(f'| **{name[a]}** | ' + ' | '.join(CELL[m(a, d)] for d in ids) + ' |')
    out += ['', '| 属性 | 克制（2×） | 被抵抗（½） | 无效（0） | 弱点（受 2×） | 抵抗（受 ½） | 免疫（受 0） |', '|---|---|---|---|---|---|---|']
    j = lambda xs: '、'.join(name[x] for x in xs) or '—'
    for t in ids:
        row = [[d for d in ids if m(t, d) == v] for v in (2, 0.5, 0)] + [[a for a in ids if m(a, t) == v] for v in (2, 0.5, 0)]
        out.append(f'| {name[t]} `{t}` | ' + ' | '.join(j(x) for x in row) + ' |')
    statuses = {s['id']: s['nameZh'] for s in json.loads((ROOT / 'content' / 'statuses.json').read_text())}
    out += ['', '| 异常状态 | 免疫属性 |', '|---|---|']
    for s, ts in data.get('statusImmunities', {}).items():
        out.append(f'| {statuses.get(s, s)} `{s}` | {j(ts)} |')
    return '\n'.join(out)


def main():
    data = json.loads((ROOT / 'content' / 'types.json').read_text())
    doc = DOC.read_text()
    head, rest = doc.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f'{head}{BEGIN}\n{render(data)}\n{END}{tail}'
    if '--check' in sys.argv:
        sys.exit(0 if new == doc else 1)
    DOC.write_text(new)
    print(f'updated {DOC.relative_to(ROOT)}')


main()
