// FrontierProvider: the ChunkProvider of the infinite overworld. Chunks inside the core rectangle are cut from
// the finished core continent map (objects bucketed by anchor chunk); every other chunk is generated by
// chunk.ts from (seed, cx, cy) alone. Sites, road edges, layouts, regions, interiors and sample sheets are kept in
// bounded LRU caches, so memory stays flat however far the player walks.
import type { BiomeId, ChunkProvider, GameMap, GroundItemDef, LightDef, MapChunk, NpcDef, PropPlacement, RegionDef, SignDef, TownDef, Warp } from '../../types.ts'
import { CONTENT } from '../../content/index.ts'
import type { BaseDeps } from './base.ts'
import { CHUNK_BIOME, compileScatter, generateFrontierChunk, type ChunkDeps } from './chunk.ts'
import type { DecorSite } from './decorate.ts'
import { Fields, newColumn, type Gateway } from './fields.ts'
import { buildDungeonFloors, buildHamletInterior } from './interiors.ts'
import { buildSiteLayout, frontierWorldContent, siteTown } from './layout.ts'
import { Lru } from './lru.ts'
import { nearestProvince, provincesNear, regionId, RegionTable } from './regions.ts'
import { RoadNet } from './roads.ts'
import { parseFrontierId, SiteGrid, type FrontierSite, type Gate } from './sites.ts'

export interface FrontierInit {
  seed: number
  overworldId: string
  /** The finished core continent (finite overworld map). Read lazily, so story additions are included. */
  core: GameMap
  /** Causeway gates found on the core coast (OverworldResult.gates). */
  gates: Gate[]
  /** World origin (overworld spawn) — distance / difficulty / latitude reference. */
  origin: { x: number; y: number }
  /** Places on the core (world.towns); read lazily. */
  corePlaces?: () => readonly TownDef[]
}

interface CoreObjects {
  props: PropPlacement[]; npcs: NpcDef[]; signs: SignDef[]; items: GroundItemDef[]; warps: Warp[]; lights: LightDef[]; places: TownDef[]
}

interface SampleSheet { terrain: Uint8Array; level: Uint8Array; biome: Uint8Array }

const key = (cx: number, cy: number) => `${cx},${cy}`

export class FrontierProvider implements ChunkProvider {
  readonly seed: number
  readonly size: number
  readonly core: { x: number; y: number; width: number; height: number }
  readonly overworldId: string
  readonly fields: Fields
  readonly grid: SiteGrid
  readonly roads: RoadNet
  readonly regions: RegionTable
  readonly gates: readonly Gate[]
  private readonly coreMap: GameMap
  private readonly corePlaces: () => readonly TownDef[]
  private readonly deps: ChunkDeps
  private readonly chunks: Lru<string, MapChunk>
  private readonly layouts: Lru<string, DecorSite>
  private readonly interiors: Lru<string, GameMap>
  private readonly sheets: Lru<string, SampleSheet>
  private readonly misses: Lru<string, number>
  private coreBuckets: Map<string, CoreObjects> | null = null
  private coreRegionIds: string[] | null = null
  private coreRegionById: Map<string, RegionDef> | null = null
  private readonly col = newColumn()
  /** Last chunk returned by chunk() (tile walks hit the same chunk many times in a row). */
  private last: MapChunk | null = null

  constructor(init: FrontierInit) {
    this.seed = init.seed
    this.overworldId = init.overworldId
    this.coreMap = init.core
    this.corePlaces = init.corePlaces ?? (() => [])
    this.gates = init.gates
    this.core = { x: 0, y: 0, width: init.core.width, height: init.core.height }
    const gateways: Gateway[] = init.gates.map((g) => ({ x: g.x, y: g.y }))
    this.fields = new Fields(init.seed, this.core, init.origin, gateways)
    const gen = this.fields.cf.fc.gen
    this.size = gen.chunkSize
    if (this.core.width % this.size !== 0 || this.core.height % this.size !== 0) {
      throw new Error(`frontier: core ${this.core.width}x${this.core.height} is not a multiple of chunkSize ${this.size}`)
    }
    this.grid = new SiteGrid(this.fields, init.gates)
    this.roads = new RoadNet(this.fields, this.grid)
    this.regions = new RegionTable(this.fields)
    const base: BaseDeps = { fields: this.fields, grid: this.grid, roads: this.roads }
    this.deps = {
      ...base,
      size: this.size,
      overworldId: this.overworldId,
      decorSite: (s) => this.decorSite(s),
      region: (id) => this.region(id),
      nestRegionId: (s) => `${s.id}:nest`,
      padRegionId: (s) => (s.type === 'hamlet' ? s.id : null),
      scatter: compileScatter(init.seed, base),
    }
    const c = gen.cache
    this.chunks = new Lru(c.chunks)
    this.layouts = new Lru(c.layouts)
    this.interiors = new Lru(c.interiors)
    this.sheets = new Lru(c.sampleChunks)
    this.misses = new Lru(c.sampleCounters)
  }

  // ---------------------------------------------------------------------------------------------- chunks

  /** True when the chunk lies inside the core continent (cut from the core map). */
  inCoreChunk(cx: number, cy: number): boolean {
    const S = this.size
    return cx >= 0 && cy >= 0 && (cx + 1) * S <= this.core.width && (cy + 1) * S <= this.core.height
  }

  chunk(cx: number, cy: number): MapChunk {
    const last = this.last
    if (last && last.cx === cx && last.cy === cy) return last
    const k = key(cx, cy)
    let ch = this.chunks.get(k)
    if (!ch) {
      ch = this.inCoreChunk(cx, cy) ? this.coreChunk(cx, cy) : generateFrontierChunk(this.deps, cx, cy)
      this.chunks.set(k, ch)
    }
    this.last = ch
    return ch
  }

  peek(cx: number, cy: number): MapChunk | null {
    return this.chunks.peek(key(cx, cy)) ?? null
  }

  /** Frontier chunk generation only (no core lookup, no cache) — tests / tools. */
  generate(cx: number, cy: number): MapChunk {
    return generateFrontierChunk(this.deps, cx, cy)
  }

  private buckets(): Map<string, CoreObjects> {
    if (this.coreBuckets) return this.coreBuckets
    const S = this.size
    const out = new Map<string, CoreObjects>()
    const at = (x: number, y: number): CoreObjects => {
      const k = key(Math.floor(x / S), Math.floor(y / S))
      let b = out.get(k)
      if (!b) { b = { props: [], npcs: [], signs: [], items: [], warps: [], lights: [], places: [] }; out.set(k, b) }
      return b
    }
    const m = this.coreMap
    for (const o of m.props) at(o.x, o.y).props.push(o)
    for (const o of m.npcs) at(o.x, o.y).npcs.push(o)
    for (const o of m.signs) at(o.x, o.y).signs.push(o)
    for (const o of m.items) at(o.x, o.y).items.push(o)
    for (const o of m.warps) at(o.x, o.y).warps.push(o)
    for (const o of m.lights) at(o.x, o.y).lights.push(o)
    for (const t of this.corePlaces()) if (t.map === this.overworldId) at(t.x, t.y).places.push(t)
    this.coreBuckets = out
    return out
  }

  private coreChunk(cx: number, cy: number): MapChunk {
    const S = this.size, m = this.coreMap, W = m.width
    const ox = cx * S, oy = cy * S
    if (!this.coreRegionIds) this.coreRegionIds = m.regions.map((r) => r.id)
    const ch: MapChunk = {
      cx, cy, size: S, terrain: new Uint8Array(S * S), elevation: new Uint8Array(S * S), region: new Uint8Array(S * S), regionIds: this.coreRegionIds,
      props: [], npcs: [], signs: [], items: [], warps: [], lights: [], places: [],
    }
    const biome = new Uint8Array(S * S)
    const regionBiome = m.regions.map((r) => { const i = CONTENT.biomes.findIndex((b) => b.id === r.biome); return i < 0 ? 0 : i })
    for (let y = 0; y < S; y++) {
      const src = (oy + y) * W + ox
      ch.terrain.set(m.terrain.subarray(src, src + S), y * S)
      ch.elevation.set(m.elevation.subarray(src, src + S), y * S)
      ch.region.set(m.region.subarray(src, src + S), y * S)
      for (let x = 0; x < S; x++) biome[y * S + x] = regionBiome[m.region[src + x]] ?? 0
    }
    const b = this.buckets().get(key(cx, cy))
    if (b) Object.assign(ch, { props: b.props, npcs: b.npcs, signs: b.signs, items: b.items, warps: b.warps, lights: b.lights, places: b.places })
    CHUNK_BIOME.set(ch, biome)
    return ch
  }

  /** Re-read the core map (call after mutating its tiles / objects at runtime, e.g. an opened gate). */
  invalidateCore(): void {
    this.coreBuckets = null
    this.coreRegionIds = null
    this.coreRegionById = null
    for (const k of [...this.chunks.keys()]) {
      const [cx, cy] = k.split(',').map(Number)
      if (this.inCoreChunk(cx, cy)) this.chunks.delete(k)
    }
    this.last = null
  }

  /** Drops every cache (e.g. after registering decorators late). */
  clearCache(): void {
    this.chunks.clear(); this.layouts.clear(); this.interiors.clear(); this.sheets.clear(); this.misses.clear()
    this.coreBuckets = null; this.coreRegionIds = null; this.coreRegionById = null
    this.last = null
  }

  retain(points: { x: number; y: number }[], radiusTiles: number): void {
    const S = this.size
    const r = radiusTiles + S * 0.7072
    const far = (cx: number, cy: number) => {
      const mx = (cx + 0.5) * S, my = (cy + 0.5) * S
      return points.every((p) => (p.x - mx) * (p.x - mx) + (p.y - my) * (p.y - my) > r * r)
    }
    for (const lru of [this.chunks, this.sheets] as Lru<string, unknown>[]) {
      for (const k of [...lru.keys()]) {
        const [cx, cy] = k.split(',').map(Number)
        if (far(cx, cy)) lru.delete(k)
      }
    }
    if (this.last && !this.chunks.has(key(this.last.cx, this.last.cy))) this.last = null
  }

  // ---------------------------------------------------------------------------------------------- sites

  /** Layout + place + centre region of a frontier site (cached). */
  decorSite(site: FrontierSite): DecorSite {
    const hit = this.layouts.get(site.id)
    if (hit) return hit
    const F = this.fields
    F.columnAt(site.x, site.y, this.col)
    const provs = provincesNear(F, site.x, site.y, site.x + 1, site.y + 1)
    const p = provs[nearestProvince(provs, site.x + this.col.pwx, site.y + this.col.pwy)]
    const region = this.regions.get(regionId(p.px, p.py, CONTENT.biomes[site.biome]?.id ?? CONTENT.biomes[0].id))
    const levelRange = region?.levelRange ?? [1, 1]
    const layout = buildSiteLayout(this.deps, site, levelRange, region?.nameZh ?? '', this.overworldId)
    const place = siteTown(layout, this.overworldId, F.cf.fc.decor.placeDescriptions, region?.nameZh ?? '')
    const ds: DecorSite = { site, layout, place, region }
    this.layouts.set(site.id, ds)
    return ds
  }

  /** The site addressed by a frontier id ('fx:<kind>:<sx>:<sy>[:<part>]'), or null. */
  siteOf(id: string): { site: FrontierSite; part: string | null } | null {
    const p = parseFrontierId(id)
    if (!p) return null
    const site = this.grid.siteAt(p.sx, p.sy)
    if (!site || site.kind.id !== p.kind) return null
    return { site, part: p.part }
  }

  place(id: string): TownDef | null {
    const s = this.siteOf(id)
    if (s) return s.part === null ? this.decorSite(s.site).place : null
    return this.corePlaces().find((t) => t.id === id) ?? null
  }

  /** Places (hamlets / landmarks / dungeons) whose site centre lies in the rect — generates layouts, not chunks. */
  placesIn(x0: number, y0: number, x1: number, y1: number): TownDef[] {
    const out: TownDef[] = []
    for (const s of this.grid.sitesNear(x0, y0, x1, y1, 0)) {
      if (!s.kind.place) continue
      const p = this.decorSite(s).place
      if (p) out.push(p)
    }
    for (const t of this.corePlaces()) if (t.map === this.overworldId && t.x >= x0 && t.y >= y0 && t.x < x1 && t.y < y1) out.push(t)
    return out
  }

  // ---------------------------------------------------------------------------------------------- regions

  region(id: string): RegionDef | null {
    if (id.startsWith('fr:')) return this.regions.get(id)
    const s = this.siteOf(id)
    if (s) {
      const { site, part } = s
      if (part === null && site.type === 'hamlet') {
        return this.regions.memo(id, () => {
          const ds = this.decorSite(site)
          const under = ds.region
          return {
            id, nameZh: ds.layout.nameZh, biome: under?.biome ?? CONTENT.biomes[site.biome].id, music: frontierWorldContent(this.deps).pois.hamlets.music,
            weather: under?.weather, encounters: [], encounterRate: 0, roamingDensity: 0, isTown: true, townId: id, danger: 0,
            flySpawn: { ...ds.layout.center }, levelRange: under?.levelRange,
          }
        })
      }
      if (part === 'nest') {
        const ds = this.decorSite(site)
        const tpl = this.grid.templates[site.template]
        if (!tpl?.nest || !ds.region) return null
        return this.regions.nest(id, ds.region, tpl.nest, ds.layout.nameZh, site.dist)
      }
      return null
    }
    if (!this.coreRegionById) {
      this.coreRegionById = new Map()
      for (const r of this.coreMap.regions) if (!this.coreRegionById.has(r.id)) this.coreRegionById.set(r.id, r)
    }
    return this.coreRegionById.get(id) ?? null
  }

  // ---------------------------------------------------------------------------------------------- interiors

  interior(mapId: string): GameMap | null {
    const hit = this.interiors.get(mapId)
    if (hit) return hit
    const s = this.siteOf(mapId)
    if (!s || s.part === null) return null
    const ds = this.decorSite(s.site)
    if (s.site.type === 'hamlet') {
      const door = ds.layout.doors.find((d) => d.mapId === mapId)
      if (!door) return null
      const m = buildHamletInterior(this.deps, ds.layout, door, this.overworldId, ds.region)
      if (m) this.interiors.set(mapId, m)
      return m
    }
    if (s.site.type === 'dungeon') {
      const floors = buildDungeonFloors(this.deps, ds.layout, this.overworldId, ds.region?.danger ?? 0)
      for (const f of floors) this.interiors.set(f.id, f)
      return floors.find((f) => f.id === mapId) ?? null
    }
    return null
  }

  // ---------------------------------------------------------------------------------------------- sample

  sample(x: number, y: number): { terrain: number; elevation: number; biome: BiomeId } {
    const tx = Math.floor(x), ty = Math.floor(y)
    const m = this.coreMap
    if (tx >= 0 && ty >= 0 && tx < m.width && ty < m.height) {
      const i = ty * m.width + tx
      return { terrain: m.terrain[i], elevation: m.elevation[i], biome: m.regions[m.region[i]]?.biome ?? CONTENT.biomes[0].id }
    }
    const S = this.size
    const cx = Math.floor(tx / S), cy = Math.floor(ty / S)
    const li = (ty - cy * S) * S + (tx - cx * S)
    const k = key(cx, cy)
    const ch = this.chunks.peek(k)
    if (ch) {
      const b = CHUNK_BIOME.get(ch)
      return { terrain: ch.terrain[li], elevation: ch.elevation[li], biome: CONTENT.biomes[b ? b[li] : 0].id }
    }
    let sh = this.sheets.get(k)
    if (!sh) {
      const n = (this.misses.get(k) ?? 0) + 1
      if (n < this.fields.cf.fc.gen.sampleSheetAfter) {
        this.misses.set(k, n)
        this.fields.columnAt(tx, ty, this.col)
        return { terrain: this.col.terrain, elevation: this.col.level, biome: CONTENT.biomes[this.col.biome].id }
      }
      this.misses.delete(k)
      sh = this.sampleSheet(cx, cy)
      this.sheets.set(k, sh)
    }
    return { terrain: sh.terrain[li], elevation: sh.level[li], biome: CONTENT.biomes[sh.biome[li]].id }
  }

  /** Natural columns of one chunk (no roads / sites / layers): what sample() reports for ungenerated chunks. */
  private sampleSheet(cx: number, cy: number): SampleSheet {
    const S = this.size, F = this.fields
    const ox = cx * S, oy = cy * S
    const sheet = F.sheet(ox, oy, ox + S - 1, oy + S - 1)
    const out: SampleSheet = { terrain: new Uint8Array(S * S), level: new Uint8Array(S * S), biome: new Uint8Array(S * S) }
    const col = this.col
    for (let y = 0; y < S; y++) for (let x = 0; x < S; x++) {
      F.column(ox + x, oy + y, sheet, col)
      const i = y * S + x
      out.terrain[i] = col.terrain; out.level[i] = col.level; out.biome[i] = col.biome
    }
    return out
  }

  // ---------------------------------------------------------------------------------------------- misc

  /** Distance (tiles) from the world origin. */
  distance(x: number, y: number): number { return this.fields.originDist(x, y) }

  /** Keeps JSON.stringify(world) finite (the provider references the core map that references it). */
  toJSON(): { seed: number; size: number; core: FrontierProvider['core']; infinite: true } {
    return { seed: this.seed, size: this.size, core: this.core, infinite: true }
  }
}
